= Devtools

This repository encapsulates configurations for some of my development tools including Visual Studio Code and Windows Terminal, as well as command line utilities including jq and LazyGit, and Windows ports of Unix looks like `make` and `wget`.

I maintain this repository to make it easier to port configurations between different computers.

.Devtools vs Dotfiles
****
My devtools are for Windows. I also maintain a link:https://github.com/kieranpotts/dotfiles[dotfiles] repository that captures further devtools configuration for UNIX-like environments. On Windows, the dotfiles should be installed on a guest OS such as WSL2 or an emulator like Git Bash. The devtools should be installed on the host OS.
****

== Documentation

* link:./docs/requirements.adoc[Requirements]
* link:./docs/installation.adoc[Installation]
* link:./docs/maintenance.adoc[Maintenance]

''''
Copyright © 2020-present Kieran Potts, link:./LICENSE.txt[MIT License]

The font files and executable binaries redistributed via this repository are copyright their respective authors and may be subject to alternative free and open source software licenses.
