= Requirements

All dependencies are OPTIONAL.

The dotfiles and Git aliases are compatible with UNIX-like environments. https://gitforwindows.org/[Git Bash for Windows] is supported. On Windows, WSL2 and required virtualization should be enabled, and "Ubuntu" installed via the Microsoft Store.

The Git configuration has been tested with https://git-scm.com/[Git] v29. It is recommended also to install https://github.com/dandavison/delta[Delta], a paging utility. The Git configuration swaps `less` for `delta` for paging output from commands like `git log` and `git diff`.

Configurations are also included for the following programs:

* https://github.com/jesseduffield/lazygit#installation[LazyGit]
* https://neovim.io/[Neovim]
* https://ohmyposh.dev/[Oh-My-Posh]
* https://www.sublimemerge.com/[Sublime Merge]
* https://code.visualstudio.com/[Visual Studio Code]
* https://github.com/microsoft/terminal[Windows Terminal]

== Bundled binaries

Windows binaries for `delta`, `lazygit` and `oh-my-posh` are included in this repository. These can be enabled simply by adding this repository's `bin` directory to your system's `PATH` environment variable. For Unix-like environments, these binaries must be installed manually. Follow the links below for installation instructions:

* link:https://dandavison.github.io/delta/installation.html[Delta] (On Ubuntu/ WSL, `git-delta` is bundled with the `git-extras` package and can therefore be installed using `sudo apt install git-extras`.)
* link:https://github.com/jesseduffield/lazygit[LazyGit]
* link:https://ohmyposh.dev/docs/installation/linux[Oh-My-Posh]

All other dependencies must be manually installed on all systems.

****
Fresh Windows binaries can be downloaded from the following links. Binaries for the x86-64 or AMD64 architectures are used.

* https://github.com/dandavison/delta/releases
* https://github.com/jesseduffield/lazygit/releases
* https://github.com/JanDeDobbeleer/oh-my-posh/releases
****
