= Requirements

The dotfiles and Git aliases are compatible with UNIX-like environments. https://gitforwindows.org/[Git Bash for Windows] is supported. On Windows, WSL2 (and the required virtualization) should be enabled, and "Ubuntu" installed via the Microsoft Store.

The Git configuration has been tested with https://git-scm.com/[Git] v2.39.1 and is known to be incompatible with versions before v2.35. https://gitforwindows.org/[Git for Windows] is recommended for the Windows platform. For Debian distros, run the following command to check which is the current version of Git available via the APT package manager.

[source,sh]
----
apt-cache policy git
----

If the available version is >= v2.35, go ahead and install it using the following commands.

[source,sh]
----
sudo apt-get update
sudo apt-get install git -y
----

Alternatively you can specify the version of a package to install, using either of the following commands.

[source,sh]
----
sudo apt-get install <package-name>=<package-version-number>
sudo apt-get -t=<target release> install <package-name>
----

Check the installed version with the command `git --version`.

If you want to install a newer version of Git than is available via the default package registries, use `wget` to download the version directly from the source. For example, to download the source for Git v2.35.0, run the following command.

[source,sh]
----
wget https://github.com/git/git/archive/refs/tags/v2.35.0.tar.gz
----

Before extracting the package, install the following packages.

[source,sh]
----
sudo apt-get update
sudo apt-get install libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc
----

Extract the Git package, then navigate to the extracted directory (path names may differ).

[source,sh]
----
tar -zxf v2.35.0.tar.gz
cd git-2.35.0
----

Run the following command to install the package. This is a slow operation.

[source,sh]
----
make prefix=/usr/local all
sudo make prefix=/usr/local install
----

Restart your terminal then check the installed Git version with the command `git --version`. Use `rm` to remove the temporary files and directories.

Some repositories use https://git-lfs.com/[Git Large File Storage]. This is a Git extension that removes large files from the repository and stores them elsewhere, cross-referenced from the Git repository using pointers. To install Git LFS, first download and install the Git command line extension from the https://git-lfs.com/[Git LFS website]. Git LFS is available for the APT package manager – `sudo apt-get install git-lfs` – else see the https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md[installation instructions].

Then run the following command:

[source,sh]
----
git lfs install
----

In each Git repository where you want to use Git LFS, run the following command to configure the file types that you'd like Git LFS to manage, or edit the `.gitattributes` file directly (this file MUST be committed).

[source,sh]
----
git lfs track "*.pdf"
----

Then commit and push as you normally would. To convert existing files, already committed to the repository, use the `git lfs migrate` command. See the https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.adoc[documentation].

It is RECOMMENDED also to install https://github.com/dandavison/delta[Delta], a paging utility. The Git configuration swaps `less` for `delta` for paging output from commands like `git log` and `git diff`.

This repository also includes configurations for the following programs – all of which are OPTIONAL.

* https://github.com/jesseduffield/lazygit#installation[LazyGit]
* https://neovim.io/[Neovim]
* https://ohmyposh.dev/[Oh-My-Posh]
* https://www.sublimemerge.com/[Sublime Merge]
* https://code.visualstudio.com/[Visual Studio Code]
* https://github.com/microsoft/terminal[Windows Terminal]

== Bundled binaries

Windows binaries for `delta`, `lazygit`, `oh-my-posh` and others are included in this repository. These can be enabled simply by adding this repository's `bin/windows` directory to your system's `PATH` environment variable.

For Unix-like environments, equivalent packages must be installed manually. Follow the links below for installation instructions for utilities that are not commonly pre-installed:

* link:https://dandavison.github.io/delta/installation.html[Delta] (On Ubuntu/ WSL, `git-delta` is bundled with the `git-extras` package and can therefore be installed using `sudo apt install git-extras`.)
* link:https://github.com/jesseduffield/lazygit[LazyGit]
* link:https://ohmyposh.dev/docs/installation/linux[Oh-My-Posh]

All other dependencies must be manually installed on all systems.

****
Fresh Windows binaries can be downloaded from the following links. Binaries for the x86-64 architecture – also known as also called x86_64, x64, or amd64 – are bundled. This is the 64-bit CPU architecture used in Intel and AMD processors.

* https://github.com/dandavison/delta/releases[delta]
* https://github.com/mgdm/htmlq/releases[htmlq]
* https://github.com/jqlang/jq/releases[jq]
* https://github.com/jesseduffield/lazygit/releases[lazygit]
* https://sourceforge.net/projects/ezwinports/files/[make] — search for the latest `without-guile-w32-bin` and extract the `make.exe` file from the archive.
* https://github.com/JanDeDobbeleer/oh-my-posh/releases[oh-my-posh]
* https://eternallybored.org/misc/wget/[wget] — download the latest x64 `.exe` file.
* https://www.xpdfreader.com/download.html[Xpdf] — download the Windows Xpdf command line tool, extract, and copy the contents of the `bin64` directory.
****
